### ISSUE TITLE
404 error trying to add repo 

### ISSUE THREAD

**Issue by debjitk** [kubernetes/autoscaler#3398]
I am getting 404 error for the following

`helm repo add autoscaler https://kubernetes.github.io/autoscaler`

**Comment by gjtempleton** [comment]
#3393 should resolve this once the pre-requisite actions have been done and it's been merged.

**Comment by jurgenweber** [comment]
I am still getting the problem, considering that has been merged.

**Comment by gjtempleton** [comment]
Unfortunately as mentioned in the above PR post merging, we've run into an issue with the official helm chart releaser action that we were hoping to use. It's also affecting other repos trying to adopt charts in the Kubernetes project. See helm/chart-releaser-action#33 for more information.

We're currently trying to set up a temporary workaround to deal with this in #3403

**Comment by jurgenweber** [comment]
Ok, Thanks for the explanation. Sounds frustrating.

**Comment by surajssd** [comment]
Yep saw this error today!

**Comment by denniswebb** [comment]
I'm sure you guys know, but still busted

**Comment by jurgenweber** [comment]
Yeah, it has been two weeks now. What do we think functionality will be restored? Thanks

**Comment by gjtempleton** [comment]
@jurgenweber Sorry, has this broken existing functionality?

I wasn't aware that was the case, just that this was effectively a new publish/home for the chart (which hasn't yet worked), with the existing home in the helm/charts repo still working?

**Comment by surajssd** [comment]
This is fixed now.

**Comment by gjtempleton** [comment]
Thanks for confirming.

/close
