### ISSUE TITLE
Make it optional if user wants cluster autoscaler to delete nodes despite of it having not replicated pods

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/autoscaler#351]
I have an use case where I need to deploy a lot of pods without any replication controller, cluster autoscaler detects that some nodes are under used but refuses to scale them down because they contains this pods that are not under any replication controller... can we make this optional? I'ld be very nice to have a flag for this.

Regards

**Comment by mwielgus** [comment]
What is the goal of having pods that you can loose at any time?

**Comment by felipejfc** [comment]
I cant loose them at any time, I can kill them if its gracefull. The reason is that I replicate them on my own.

**Comment by mwielgus** [comment]
I would rather have a special annotation on a pod (saying that it is OK to delete this particular pod) instead of a global switch - in a single cluster you might have both pods that you can delete and others that cannot be deleted.

**Comment by aleksandra-malinowska** [comment]
Fixed in #418

**Comment by sstarcher** [comment]
@mwielgus What about the usecase of a development cluster that tons of people can launch pods into, but we still want to scale these down?  Would it not be beneficial to also support a global flag?  If not I now have to write some code that goes through the pods and annotates them.

**Comment by drewhemm** [comment]
I am using the `cluster-autoscaler.kubernetes.io/safe-to-evict=true` annotation, but I am still seeing messages like this in the autoscaler logs:

```
I0125 11:23:10.132575       1 cluster.go:89] Fast evaluation: node ip-192-168-70-10.eu-west-1.compute.internal cannot be removed: kube-system/kube-proxy-rbpck is not replicated
```

Am I doing something wrong?

**Comment by aleksandra-malinowska** [comment]
kube-proxy should have annotation "kubernetes.io/config.mirror". What Kubernetes version are you using and how was kube-proxy (or the cluster) deployed?

**Comment by drewhemm** [comment]
I've tried with both 1.10.11 and 1.11.5. Cluster is deployed via AWS EKS. The "kubernetes.io/config.mirror" annotation is not present out-of-the-box. Are you saying I should add it?

I am also having the same issue with the aws-node daemonset, even though I have set PodDisruptionBudgets for both. 

Autoscaling is working fine for me in Google GKE.

**Comment by aleksandra-malinowska** [comment]
kube-proxy had this annotation for a very long time now, and it's the only way Cluster Autoscaler is able to recognize it as runs-on-every-node-don't-care-about-it-pod. I'd suggest adding it back if possible. 

> I am also having the same issue with the aws-node daemonset, even though I have set PodDisruptionBudgets for both:

Pods controlled by DaemonSet should be ignored by default, can you share the yaml?

**Comment by drewhemm** [comment]
Tried adding that annotation - didn't get very far:

```
# daemonsets "kube-proxy" was not valid:
# * spec.template.annotations[kubernetes.io/config.mirror]: Invalid value: "": must set spec.nodeName if mirror pod annotation is set
```
Here's the yaml for the DS on a freshly spun-up EKS cluster

```
kubectl get ds kube-proxy -n kube-system -o yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"eks.amazonaws.com/component":"kube-proxy","k8s-app":"kube-proxy"},"name":"kube-proxy","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"kube-proxy"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"k8s-app":"kube-proxy"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/os","operator":"In","values":["linux"]},{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]}]}}},"containers":[{"command":["/bin/sh","-c","kube-proxy --resource-container=\"\" --oom-score-adj=-998 --master=https://d077476afc89dcee0821e2152be7abef.sk1.eu-west-1.eks.amazonaws.com --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --v=2 1\u003e\u003e/var/log/kube-proxy.log 2\u003e\u00261"],"image":"############.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.11.5","name":"kube-proxy","resources":{"requests":{"cpu":"100m"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/log","name":"varlog","readOnly":false},{"mountPath":"/run/xtables.lock","name":"xtables-lock","readOnly":false},{"mountPath":"/var/lib/kube-proxy/","name":"kubeconfig"}]}],"hostNetwork":true,"serviceAccountName":"kube-proxy","tolerations":[{"effect":"NoExecute","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/log"},"name":"varlog"},{"hostPath":{"path":"/run/xtables.lock","type":"FileOrCreate"},"name":"xtables-lock"},{"configMap":{"name":"kube-proxy"},"name":"kubeconfig"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":"10%"},"type":"RollingUpdate"}}}
  creationTimestamp: 2019-01-25T14:08:48Z
  generation: 1
  labels:
    eks.amazonaws.com/component: kube-proxy
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "166"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/kube-proxy
  uid: bc3a8169-20aa-11e9-a488-02ec632c4688
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - command:
        - /bin/sh
        - -c
        - kube-proxy --resource-container="" --oom-score-adj=-998 --master=https://d077476afc89dcee0821e2152be7abef.sk1.eu-west-1.eks.amazonaws.com
          --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --v=2
          1>>/var/log/kube-proxy.log 2>&1
        image: #############.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.11.5
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /var/lib/kube-proxy/
          name: kubeconfig
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-proxy
      serviceAccountName: kube-proxy
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - configMap:
          defaultMode: 420
          name: kube-proxy
        name: kubeconfig
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  observedGeneration: 1
```

**Comment by drewhemm** [comment]
I checked GKE. The daemonset for the kube-proxy pods isn't even visible, so Google is doing some magic to ensure the pods are not an obstacle to autoscaling, which is a console-enabled feature there. 

Does anyone have autoscaling working in AWS EKS, or only in vanilla Kubernetes on standard EC2 instances?

**Comment by drewhemm** [comment]
I think I found the problem. The image tag hasn't been updated in the example yaml files, so even on a 1.2.x or 1.3.x branch, the image tag is 0.6.0. I changed this according and things are working as expected.

**Comment by sstarcher** [comment]
I had previously posted this, but I tagged the wrong individual 

@aleksandra-malinowska 
What about the usecase of a development cluster that tons of people can launch pods into, but we still want to scale these down? Would it not be beneficial to also support a global flag? If not I now have to write some code that goes through the pods and annotates them.
