### ISSUE TITLE
`skipped_scale_events_count` not working as expected (metric never emits)

### ISSUE THREAD

**Issue by zachBridges** [kubernetes/autoscaler#5122]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
app version: 9.19.4
image version: 1.23.1

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-84b4fe6", GitCommit:"c813d094d1e9fa409079753049cfaa9a67524ed2", GitTreeState:"clean", BuildDate:"2022-06-09T18:20:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What environment is this in?**:
AWS + EKS (v1.20)

**What did you expect to happen?**:
I expected to see the newly-added metric, `skipped_scale_events_count`, emitted @ the `/metrics` endpoint

**What happened instead?**:
`cluster-autoscaler` did not emit the metric, `skipped_scale_events_count`. 
The logs did not emit what I expected from [scale_up.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/scale_up.go#L431). 

**How to reproduce it (as minimally and precisely as possible)**:
1. Ensure `cluster-autoscaler` emits a log @ startup indicating it is running v1.23.1. 
2. Modify replicas for a pod that requests 1 CPU, 2Gi (request and limits equal) from 1 -> N (where N is very large)
  * This causes the `clutser-autoscaler` to hit the max # of nodes. As a result, many pods will remain unschedulable.
3. Observe logs for `cluster-autoscaler` 
4. Hit the `/metrics` endpoint of the `cluster-autoscaler` and observe that the expected metric, `skipped_scale_events_count`, is not present.

**Anything else we need to know?**:

### Logs from `scale_up.go`: 
```
I0824 14:14:45.581353       1 scale_up.go:376] Upcoming 0 nodes
I0824 14:14:45.581636       1 scale_up.go:412] Skipping node group platform-dev-eks - max size reached
I0824 14:14:45.581650       1 scale_up.go:412] Skipping node group platform-dev-eks-ephemeral - max size reached
I0824 14:14:45.581655       1 scale_up.go:453] No expansion options
```
Seeing these logs indicates to me that `if currentTargetSize >= nodeGroup.MaxSize()` is the condition my `cluster-autoscaler` is hitting. 
Based on the description of `skipped_scale_events_count`, either: 
* I do not understand scale events or
* Emitting a different, new metric may be useful for when `currentTargetSize >= nodeGroup.MaxSize()`

Thanks in advance

**Comment by zachBridges** [comment]
@elmiko :wave: Tagging you in this since my issue relates to a feature you recently added.

**Comment by elmiko** [comment]
good find @zachBridges , i think this is just an oversight on how that metric works currently. currently, it will only register skipped events when the memory or cpu limits are reached. it would be great to add another clause for increasing the metric when the cluster reaches it maximum or minimum size.

i can probably take a look at adding cluster size to the skipped metric sometime next week, but happy to review any PRs if you have ideas =)

**Comment by zachBridges** [comment]
@elmiko 
Thanks for your reply! 

Do you imagine something along the lines of the following?
```go
// metrics.go
// RegisterSkippedScaleUpNodeGroupMaxSize increases the count of skipped scale outs 
//   because node group has reached maximum configured size
func RegisterSkippedScaleUpNodeGroupMaxSize() {
	skippedScaleEventsCount.WithLabelValues(DirectionScaleUp, NodeGroupLimit).Add(1.0)
}
```

and then emitting that metric within the condition, 

```go
// scale_up.go
if currentTargetSize >= nodeGroup.MaxSize() {
  klog.V(4).Infof("Skipping node group %s - max size reached", nodeGroup.Id())
  skippedNodeGroups[nodeGroup.Id()] = maxLimitReachedReason
  metrics.RegisterSkippedScaleUpNodeGroupMaxSize() // emit the new metric
  continue
}
```

**Comment by elmiko** [comment]
yeah, that looks pretty close to what i was thinking =)

**Comment by sebradloff** [comment]
@elmiko @zachBridges would love both of your input/feedback on #5175 😄 
I implemented what y'all were suggesting above and a little more.

**Comment by elmiko** [comment]
that's awesome, thanks @sebradloff !

**Comment by elmiko** [comment]
keeping this open as we still have a PR, but it needs some help

/remove-lifecycle rotten
