### ISSUE TITLE
v1.26.0 runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [kubernetes/autoscaler#5389]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
Chart Version: 9.21.1
App Version: v1.26.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
</pre></details>

**What environment is this in?**:

EKS 1.23

**What did you expect to happen?**:

just working without error

**What happened instead?**:
panic with runtime error as below
```
│ panic: runtime error: invalid memory address or nil pointer dereference                                                                     │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x3cfca79]                                                                    │
│                                                                                                                                             │
│ goroutine 72 [running]:                                                                                                                     │
│ k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling.(*HintingSimulator).findNode(0xc000c03050, 0x5a2fdc0?, {0x5a2fdc0, 0xc00034e868}, │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling/hinting_simulator.go:114 +0x159                                   │
│ k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling.(*HintingSimulator).TrySchedulePods(0x40a5c00?, {0x5a2fdc0, 0xc00034e868}, {0xc00 │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling/hinting_simulator.go:70 +0x2cf                                    │
│ k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*filterOutSchedulablePodListProcessor).filterOutSchedulableByPacking(0xc00034e8 │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/filter_out_schedulable.go:101 +0x111                             │
│ k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*filterOutSchedulablePodListProcessor).Process(0x0?, 0xc002a7d800, {0xc002ca810 │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/filter_out_schedulable.go:66 +0xd5                               │
│ k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*defaultPodListProcessor).Process(0xc000c0ec50, 0xc002c96db0?, {0xc002ca8100?,  │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/pod_list_processor.go:45 +0x65                                   │
│ k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc00099c960, {0x4?, 0x0?, 0x87e1e20?})                               │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:477 +0x1ca3                                                  │
│ main.run(0xc000b10a00?, {0x5a277b8, 0xc000a8a0f0})                                                                                          │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:442 +0x2cd                                                                     │
│ main.main.func2({0x0?, 0xc000959ec0?})                                                                                                      │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:529 +0x25                                                                      │
│ created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run                                                                       │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b             
```

**How to reproduce it (as minimally and precisely as possible)**:

I'm using helm-chart 9.21.1 version 

```
  - name: cluster-autoscaler
    repository: https://kubernetes.github.io/autoscaler
    version: "9.21.1"
```

and below is my overrides.

```yaml
cluster-autoscaler:
  autoDiscovery:
    clusterName: temp-dev
  extraArgs:
    scale-down-unneeded-time: 1h
  image:
    tag: v1.26.0
  rbac:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::945962818829:role/eks_temp-dev_cluster-autoscaler
  fullnameOverride: cluster-autoscaler
  cloudProvider: aws
  awsRegion: ap-northeast-1
  rbac:
    serviceAccount:
      create: true
      name: cluster-autoscaler
```

**Anything else we need to know?**:
If I use v1.25.0 it works fine : )

**Comment by ruudvanderweijde** [comment]
Looks similar to: https://github.com/kubernetes/autoscaler/issues/5378

**Comment by 0xF4D3C0D3** [comment]
@ruudvanderweijde thanks I'll close this issue

**Comment by towca** [comment]
FYI this is now fixed in Cluster Autoscaler 1.26.1: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.26.1. I tested a basic scale-up/down scenario on GCE and everything looked ok.

**Comment by Kampe** [comment]
I still see the same issue on `v1.26.4-eks-0a21954` 

Using autoscaler 1.27.1 ...
```
cluster-autoscaler              kube-system             2               2023-06-13 00:01:53.736343 -0500 CDT    deployed        cluster-autoscaler-9.29.0               1.27.1 
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x3cfca79]

goroutine 92 [running]:
k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling.(*HintingSimulator).findNode(0xc000d2c030, 0x5a2fdc0?, {0x5a2fdc0, 0xc00019cad8}, 0xc000f81300, 0x1607cb5?)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling/hinting_simulator.go:114 +0x159
k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling.(*HintingSimulator).TrySchedulePods(0x40a5c00?, {0x5a2fdc0, 0xc00019cad8}, {0xc001b2d710, 0x2, 0x4f2fca0?}, 0xc000b908f0?, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling/hinting_simulator.go:70 +0x2cf
k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*filterOutSchedulablePodListProcessor).filterOutSchedulableByPacking(0xc00019cae8, {0xc001b2d710, 0x2, 0x2}, {0x5a2fdc0, 0xc00019cad8})
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/filter_out_schedulable.go:101 +0x111
k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*filterOutSchedulablePodListProcessor).Process(0x0?, 0xc00187e400, {0xc001b2d710?, 0x2, 0x2})
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/filter_out_schedulable.go:66 +0xd5
k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*defaultPodListProcessor).Process(0xc000d3a0f0, 0xc00159ef30?, {0xc001b2d710?, 0x3?, 0x2?})
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/pod_list_processor.go:45 +0x65
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc001a1ad20, {0x4?, 0xc0000bb710?, 0x87e1e20?})
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:477 +0x1ca3
main.run(0xc000c70a00?, {0x5a277b8, 0xc000aa0a80})
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:442 +0x2cd
main.main.func2({0x8ced06?, 0xc0001bcd70?})
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:529 +0x25
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b
        ```

**Comment by towca** [comment]
I think somehow you're still running Cluster Autoscaler 1.26.0 - even the line numbers in the stacktrace don't match what's there in 1.27.2. Could you verify:
1. The CA image used, by describing the CA pod after it's created.
2. The CA version logged in CA logs - CA always logs its version at startup.

I suspect both of these will show 1.26.0, even though the helm call shows 1.27.1 - AFAIU the same thing happened in https://github.com/kubernetes/autoscaler/issues/5825#issuecomment-1583785850.
