### ISSUE TITLE
cluster-autoscaler still thinks node group has taints (after untaint) and refuses to scale back up from zero count

### ISSUE THREAD

**Issue by icelava** [kubernetes/autoscaler#6452]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: cluster-autoscaler

Component version: helm chart 9.26.0 cluster-autoscaler 1.28.2

**What k8s version are you using (`kubectl version`)?**: 1.28

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde
</pre></details>

**What environment is this in?**: AWS EKS; managed node groups

**What did you expect to happen?**: Untainted node group be able launch nodes and schedule pods again.

**What happened instead?**: autoscaler still thinks node group has the long-gone node with taint and thus won't launch another node instance, even though the taint has been removed from node group.

```
│ Events:                                                                                                              │
│   Type     Reason             Age                     From                Message                                    │
│   ----     ------             ----                    ----                -------                                    │
│   Normal   NotTriggerScaleUp  22m (x385 over 19h)     cluster-autoscaler  pod didn't trigger scale-up: 3 max node gr │
│ oup size reached, 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had untolerated taint {cost: true}  │
│   Normal   NotTriggerScaleUp  12m (x179 over 19h)     cluster-autoscaler  pod didn't trigger scale-up: 3 max node gr │
│ oup size reached, 1 node(s) had untolerated taint {cost: true}, 1 node(s) didn't match Pod's node affinity/selector  │
│   Normal   NotTriggerScaleUp  7m11s (x1152 over 19h)  cluster-autoscaler  pod didn't trigger scale-up: 1 node(s) had │
│  untolerated taint {cost: true}, 1 node(s) didn't match Pod's node affinity/selector, 3 max node group size reached  │
│   Warning  FailedScheduling   5m (x161 over 19h)      default-scheduler   0/8 nodes are available: 8 node(s) didn't  │
│ match Pod's node affinity/selector. preemption: 0/8 nodes are available: 8 Preemption is not helpful for scheduling. │
│ .                                                                                                                    │
│   Normal   NotTriggerScaleUp  2m10s (x2508 over 19h)  cluster-autoscaler  pod didn't trigger scale-up: 1 node(s) did │
│ n't match Pod's node affinity/selector, 1 node(s) had untolerated taint {cost: true}, 3 max node group size reached  │
│   Normal   TriggeredScaleUp   50s                     cluster-autoscaler  pod triggered scale-up: [{eks-ZeroNodes-ce │
│ c688d4-02dd-c7f5-6bd1-be1a14735f61 0->1 (max: 1)}]                                                                   │
│   Normal   Scheduled          3s                      default-scheduler   Successfully assigned default/nginx-test t │
│ o ip-10-0-76-17.ap-southeast-1.compute.internal                                                                      │
│   Normal   Pulling            2s                      kubelet             Pulling image "nginx:latest"               │

```

**How to reproduce it (as minimally and precisely as possible)**:

Taint node group to evict pods

`aws eks update-nodegroup-config --cluster-name eks-cluster --nodegroup-name ZeroNodes --taints addOrUpdateTaints={key=cost,value=true,effect=NO_EXECUTE}`

Pods get evicted and nodes eventually terminated to zero count.

Untaint node group to re-host pods.

`aws eks update-nodegroup-config --cluster-name eks-cluster --nodegroup-name ZeroNodes --taints removeTaints={key=cost,value=true,effect=NO_EXECUTE}`

Pod remains in perpetual pending state, as per events above, with autoscaler thinking the the old node with taint still around and refuses to launch another node in its place (without the taint).

**Anything else we need to know?**:
Workaround to deliberately kill autoscaler pod, so replacement autoscaler pod with no memory of the past can correctly auto-discover the node group and launch node to host the pod as per events above.

**Comment by icelava** [comment]
Additional note on the workaround. We essentially restart the autoscaler deployment as the last step of our automation workflow.

`kubectl rollout restart deployment/aws-cluster-autoscaler -n kube-system`

**Comment by ivan-morhun** [comment]
I was experiencing the same behavior when the NodeTermination Handler marked the last node in the node pool with his taint and ASG reached 0 size. After this ClusterAutoscaler is not able to scale it up because of
```
2024-01-24T08:58:11+03:00 I0124 05:58:11.046721       1 orchestrator.go:546] Pod gitlab-runner/runner-eucgy1fpg-project-517-concurrent-1-f41lk8jv can't be scheduled on ciq-ci-gitlab-agents2023101009545070710000000e, predicate checking error: node(s) had untolerated taint {aws-node-termination-handler/asg-lifecycle-termination: asg-lifecycle-term-65653465366439612d303362612d373737302d353735}; predicateName=TaintToleration; reasons: node(s) had untolerated taint {aws-node-termination-handler/asg-lifecycle-termination: asg-lifecycle-term-65653465366439612d303362612d373737302d353735}; debugInfo=taints on node: []v1.Taint{v1.Taint{Key:"gitlab-agent", Value:"true", Effect:"NoSchedule", TimeAdded:<nil>}, v1.Taint{Key:"aws-node-termination-handler/asg-lifecycle-termination", Value:"asg-lifecycle-term-65653465366439612d303362612d373737302d353735", Effect:"NoExecute", TimeAdded:<nil>}}
```
CA pod restart helps

**Comment by linxcat** [comment]
Confirming replication of this issue on a production cluster, helm chart 9.25.0 version 1.24.0

**Comment by nooperpudd** [comment]
I have the same issues if I create mixed instance types in the same node group,  I only kept one instance type in the different node groups,  the taint feature can work if the node scales up from 0.
```yaml 
tags:
  k8s.io/cluster-autoscaler/enabled: "true"
  k8s.io/cluster-autoscaler/blocknode: "owned"
  k8s.io/cluster-autoscaler/node-template/taint/xxx.com/name: "true:NoSchedule"
```

**Comment by ivan-morhun** [comment]
The version 1.30.1 has the same issue.
Node was terminated last night, ASG has desired capacity 0, but CA still "see" the node in the cluster and doesn't scale up the ASG

```
{"ts":1719909365710.1602,"caller":"orchestrator/orchestrator.go:565","msg":"Pod jenkins-aqa/aqa-build-agent-235-qjzfw-cw6lm can't be scheduled on ciq-ci-jenkins-aqa-tests-agents20230808050032196800000003, predicate checking error: node(s) had untolerated taint {aws-node-termination-handler/asg-lifecycle-termination: asg-lifecycle-term-34363838643263332d303665352d326261662d333838}; predicateName=TaintToleration; reasons: node(s) had untolerated taint {aws-node-termination-handler/asg-lifecycle-termination: asg-lifecycle-term-34363838643263332d303665352d326261662d333838}; debugInfo=taints on node: []v1.Taint{v1.Taint{Key:\"aws-node-termination-handler/asg-lifecycle-termination\", Value:\"asg-lifecycle-term-34363838643263332d303665352d326261662d333838\", Effect:\"NoExecute\", TimeAdded:<nil>}}","v":2}
```

**Comment by mseiwald** [comment]
Isn't this fixed by [this](https://github.com/kubernetes/autoscaler/pull/6482)?

**Comment by Shubham82** [comment]
> Isn't this fixed by [this](https://github.com/kubernetes/autoscaler/pull/6482)?

Hi @icelava @ivan-morhun, Could you please check with CA v1.31, as PR #6482 is merged in CA 1.31.0
Please see the Changelog: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.31.0

**Comment by ivan-morhun** [comment]
I currently have exactly 1.31 in one cluster and the issue still exists.
CA sees the ghost "dead" node with toleration from the [NodeTermination Handler](https://github.com/aws/aws-node-termination-handler)
I restart the CA hourly to "reset" its state...
Thanks

**Comment by phiphi282** [comment]
We managed to fix the issue with the clusterAPI provider by setting the `--status-taint` flag for the autoscaler.
This way our transient taint gets ignored by the autoscaler when creating the node template.

There also is the `--node-info-cache-expire-time` flag that has a default expire time of 10 years. By setting this to a lower value you don't have to restart the pod anymore.
This also helps if the nodegroup gets changed while scaled to 0 which would also not get noticed by the autoscaler.

**Comment by ivan-morhun** [comment]
@phiphi282 Thanks for the advice.
The `--status-taint` flag doesn't suit us, whereas `--node-info-cache-expire-time` looks much better than the Jenkins job that restarts CA.

**Comment by pauldtill** [comment]
@ivan-morhun  - sorry to drag this one up, but what value are you using for `--node-info-cache-expire-time` ? 

The docs say it defaults to 10 years, but isn't clear to me, what format I should use to lower this - is it numeric e.g. seconds or some other time based format ? e.g. 24h0m0s

**Comment by ivan-morhun** [comment]
@pauldtill the same for me, I've tried to change that option, but ca fails to start.
Sorry for late reply

**Comment by icelava** [comment]
> > Isn't this fixed by [this](https://github.com/kubernetes/autoscaler/pull/6482)?
> 
> Hi [@icelava](https://github.com/icelava) [@ivan-morhun](https://github.com/ivan-morhun), Could you please check with CA v1.31, as PR [#6482](https://github.com/kubernetes/autoscaler/pull/6482) is merged in CA 1.31.0 Please see the Changelog: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.31.0

I'm not been working on the AWS/Kubernetes side of things for a long while now; I've been assigned to deal with other operational aspects (primarily Microsoft 365).

Don't think can test this since my team mates have moved forward and deployed another node manager Karpenter?

**Comment by ivan-morhun** [comment]
@icelava we use CA 1.31 right now and issue still exists

**Comment by AlexyPulivelil** [comment]
@ivan-morhun We don't need to restart CA each hour. If an issue comes up, we will restart it, and the rest of the day it will be working as expected. I will try with 1.31 maybe next week. Let's see whether the issue persists.

**Comment by pauldtill** [comment]
@phiphi282 - can you clarify what value you used for --node-info-cache-expire-time and how you evidenced that it is working, other than the issue not occurring for a while ? Is there something in the logs we can see to show the expiry is happening ? I tried using a value of "24h0m0s", but couldn't really tell is this achieved anything.

We also see this issue on 1.31 btw.

**Comment by AlexyPulivelil** [comment]
@ivan-morgun Getting issues repeatedly. Thinking of writing a cron Job to restart autoscaler Pod for may 3 or 4hr

**Comment by ghost** [comment]
@AlexyPulivelil in the helm chart values I fixed my problem by adding this `node-info-cache-expire-time: "0h30m0s"` to extraArgs.

**Comment by AlexyPulivelil** [comment]
Does that mean you don't have to restart the cluster autoscaler

**Comment by ghost** [comment]
Exactly

**Comment by pauldtill** [comment]
@ivan-morgun - did you find some way to prove this was happening from the logs ? 
I've added this to the args, but I can't see anything in the logs to confirm it has worked.
I have entires like this - 

```
I0911 12:53:24.158539       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0911 12:53:24.158630       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 30.692µs
I0911 12:55:24.159555       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0911 12:55:24.159607       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 25.142µs
I0911 12:57:24.160392       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0911 12:57:24.160456       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 26.972µs
I0911 12:59:24.161560       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0911 12:59:24.161640       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 33.812µs
I0911 13:01:24.161793       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0911 13:01:24.161854       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 30.582µs
```

But as you can see, they are happening every 2 mins - rather than 30 mins. Is this a different cache control ?

**Comment by ghost** [comment]
My proof that I don't have issues with cached node taints and no issues with scaling up the node-pools.
I have the same in logs, but this doesn't bother me)

**Comment by pauldtill** [comment]
Thanks @ivan-morgun  - guess I'll just apply it and see if the issues go away 🤠

**Comment by maxcao13** [comment]
Hi everyone. I was looking at how to solve this, and the problem arises around here in the core autoscaler code:

https://github.com/kubernetes/autoscaler/blob/6d32a56ca94d7bbef5e681efdbebc345b7eecc5e/cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go#L120-L149

The cluster autoscaler builds templates for each cloud provider implementation of "node groups." For example, in the AWS provider, a node group is an Auto Scaling Group, while in cluster-api, node groups are MachineDeployments/Pools/Sets in the cluster itself. These node templates tell the cluster autoscaler how to create new nodes to accommodate new workloads.

To build node templates for each existing node group, the cluster autoscaler uses the following prioritized methods, falling back to subsequent options if earlier ones are unavailable:

For each node group:
1. First, check existing nodes in the cluster to make node templates. This is the trivial case.
	1. These nodes must be a "good template candidate," meaning they have to be ready, schedulable, stable, and not marked for deletion.
2. If there are no good existing nodes for a particular node group, the cache is checked. The cache holds previous copies of nodes that may or may not exist in the cluster anymore.
	1. The bug occurs when a previously existing node had a taint that made it unschedulable, and the cluster autoscaler copied that state into the cache.
	2. When scaling from zero, there may be no existing nodes from step 1 that the cluster autoscaler can use, so it looks into the cache and builds a node template with a bad taint like `NoSchedule`, which prevents scale up.
3. If the cache is empty for this particular node group, we fall back to getting a node template from the cloud provider directly:
	1. `nodeGroup.TemplateNodeInfo()` is implemented by each cloud provider.
4. Finally, if we can't create node templates from any of the above methods for this particular node group, we will start looking at unready/unschedulable nodes as a last resort.

I am wondering if it makes sense to swap the order of steps 2 and 3 to solve this in most cases. I believe the cloud provider template generation function should have higher priority when creating node templates. Cached nodes can unfortunately have undesired properties such as NoSchedule taints, but they still hold value as a secondary fallback option.

Wondering if there may be any side-effects from this change, or if people have other ideas.

**Comment by maxcao13** [comment]
Talked about this in [sig-autoscaling 2025-10-09](https://docs.google.com/document/d/1RvhQAEIrVLHbyNnuaT99-6u9ZUMp7BfkPupT2LAZK7w/edit?tab=t.0#heading=h.8f925da1hmx5):

The way that cluster-autoscaler solves is by accepting the `status-taints` argument, which allows it to ignore certain specific taints that shouldn't be on every node in a homogeneous nodegroup. You can also prefix the taints you don't want CAS to take into account with `status-taint.cluster-autoscaler.kubernetes.io/`.

I believe that this was introduced in this PR: https://github.com/kubernetes/autoscaler/pull/6132

I'm re-reading this thread, and it seems this was called but still doesn't work for some people?
