### ISSUE TITLE
Failing to scale nodes with AKS

### ISSUE THREAD

**Issue by tobiasrosenhoff** [kubernetes/autoscaler#884]
I'm trying to get cluster-autoscaler working with AKS, and I get the following errors. 

Kubernetes version: v1.9.6
Cluster-autoscaler version: v1.2.2

1 scale_up.go:59] Pod default/php-apache-7ccc68c5cd-vrxzp is unschedulable
1 scale_up.go:446] No node info for: agentpool
1 static_autoscaler.go:304] Failed to scale up: failed to find template node for node group agentpool
1 static_autoscaler.go:186] 3 unregistered nodes present

I'm using the following [deployment](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-containerservice.yaml) 

**My Node labels are:**
agentpool=agentpool
beta.kubernetes.io/arch=amd64
beta.kubernetes.io/instance-type=Standard_DS1_v2
beta.kubernetes.io/os=linux
failure-domain.beta.kubernetes.io/region=westeurope
failure-domain.beta.kubernetes.io/zone=1
kubernetes.io/hostname=aks-agentpool-16882496-0
kubernetes.io/role=agent
storageprofile=managed,storagetier=Premium_LRS

I've tried looking around for answers but I haven't been able to find any clues.

**Comment by feiskyer** [comment]
@tobiasrosenhoff What's the status of cluster-autoscaler? e..g  the output of ` kubectl -n kube-system describe configmap cluster-autoscaler-status`

cc @kkmsft

**Comment by tobiasrosenhoff** [comment]
@feiskyer @kkmsft thanks for your reply. :) 

>

Name:         cluster-autoscaler-status
Namespace:    kube-system
Labels:       <none>
Annotations:  cluster-autoscaler.kubernetes.io/last-updated=2018-05-21 07:20:22.915143203 +0000 UTC

Data
\====
status:
\----
Cluster-autoscaler status at 2018-05-21 07:20:22.915143203 +0000 UTC:
Cluster-wide:
  Health:      Healthy (ready=3 unready=0 notStarted=0 longNotStarted=0 registered=3 longUnregistered=3)
               LastProbeTime:      2018-05-21 07:20:22.229424388 +0000 UTC
               LastTransitionTime: 2018-05-20 20:32:53.088181514 +0000 UTC
  ScaleUp:     NoActivity (ready=3 registered=3)
               LastProbeTime:      2018-05-21 07:20:22.229424388 +0000 UTC
               LastTransitionTime: 2018-05-20 20:32:53.088181514 +0000 UTC
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2018-05-21 07:20:22.229424388 +0000 UTC
               LastTransitionTime: 2018-05-20 20:32:53.088181514 +0000 UTC

NodeGroups:
  Name:        agentpool
  Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=3 cloudProviderTarget=3 (minSize=4, maxSize=10))
               LastProbeTime:      2018-05-21 07:20:22.229424388 +0000 UTC
               LastTransitionTime: 2018-05-20 20:32:53.088181514 +0000 UTC
  ScaleUp:     NoActivity (ready=0 cloudProviderTarget=3)
               LastProbeTime:      2018-05-21 07:20:22.229424388 +0000 UTC
               LastTransitionTime: 2018-05-20 20:32:53.088181514 +0000 UTC
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2018-05-21 07:20:22.229424388 +0000 UTC
               LastTransitionTime: 2018-05-20 20:32:53.088181514 +0000 UTC


Events:  <none>
>

**Comment by feiskyer** [comment]
According to the status, all nodes are marked as unregistered. There's possible configuration errors. Have you configured all required parameters according to [here](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/azure#aks-or-acs-deployment). Also could you check whether there are errors in autoscaler pod? e.g. by `kubectl -n kube-system logs <autoscaler-pod-name>`

**Comment by tobiasrosenhoff** [comment]
I've base64 encoded all values with lowercase. ClientID, ClientSecret and TenantID is output from "az ad sp create-for-rbac ..." command.

ClientID: appId
ClientSecret: password
ResourceGroup: The resource group where AKS i located. In our case: inception
SubscriptionID: The Subscription ID
TenantID: tenant
Deployment: Wasn't able to find this in the deployment [template?](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-containerservice.yaml)
ClusterName: inception-aks
NodeResourceGroup: mc_inception_inception-aks_westeurope


**Output from kubectl -n kube-system logs <autoscaler-pod-name>**
1 azure_manager.go:261] Refreshed ASG list, next refresh after 2018-05-21 10:34:24.583355283 +0000 UTC
1 static_autoscaler.go:186] 3 unregistered nodes present
1 utils.go:330] Removing unregistered node azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-0
1 utils.go:346] Failed to remove node azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-0: node group min size reached, skipping unregistered node removal
1 utils.go:330] Removing unregistered node azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-1
1 utils.go:346] Failed to remove node azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-1: node group min size reached, skipping unregistered node removal
1 utils.go:330] Removing unregistered node azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-2
1 utils.go:346] Failed to remove node azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-2: node group min size reached, skipping unregistered node removal
1 utils.go:456] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
1 static_autoscaler.go:280] No unschedulable pods
1 scale_down.go:446] No candidates for scale down

**Comment by kkmsft** [comment]
@tobiasrosenhoff - Thank you for trying out the AKS autoscaler. 
Can you please:
1. Increase the verbosity of the logging - by changing the following line in the command line of cluster-autoscaler to 5 (- --v=5) from 3 and provide us those logs.
2. Provide the output of the following from one of the worker nodes in the cluster
kubectl get nodes <node name> -o json | grep providerID
(note that the client version needs to be the later version (1.10.0+ is fine) for it to give the the provider ID)

**Comment by tobiasrosenhoff** [comment]
@kkmsft - Thanks for helping me out! 

**This is output from kubectl get nodes aks-agentpool-16882496-0 -o json | grep providerID**

> "providerID": "azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/MC_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-0"

**This is verbose logging when container has started**  
> static_autoscaler.go:114] Starting main loop
> azure_container_service_pool.go:86] AgentPool profile name: agentpool
> azure_container_service_pool.go:113] Got node count: 3
> azure_container_service_pool.go:393] Node Name: aks-agentpool-16882496-0, ID: /subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-0
> azure_container_service_pool.go:373] Matching agentPool name: agentpool with tag name: agentpool
> azure_container_service_pool.go:396] Returning back the providerID: azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-0
> azure_container_service_pool.go:393] Node Name: aks-agentpool-16882496-1, ID: /subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-1
> azure_container_service_pool.go:373] Matching agentPool name: agentpool with tag name: agentpool
> azure_container_service_pool.go:396] Returning back the providerID: azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-1
> azure_container_service_pool.go:393] Node Name: aks-agentpool-16882496-2, ID: /subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-2
> azure_container_service_pool.go:373] Matching agentPool name: agentpool with tag name: agentpool
> azure_container_service_pool.go:396] Returning back the providerID: azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-2
> static_autoscaler.go:186] 3 unregistered nodes present
> utils.go:456] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
> static_autoscaler.go:263] Filtering out schedulables
> static_autoscaler.go:273] No schedulable pods
> static_autoscaler.go:280] No unschedulable pods
> static_autoscaler.go:322] Calculating unneeded nodes
> azure_container_service_pool.go:86] AgentPool profile name: agentpool
> azure_container_service_pool.go:113] Got node count: 3
> **utils.go:404] Skipping aks-agentpool-16882496-1 - no node group config**
> utils.go:404] Skipping aks-agentpool-16882496-2 - no node group config
> utils.go:404] Skipping aks-agentpool-16882496-0 - no node group config
> static_autoscaler.go:352] Scale down status: unneededOnly=true lastScaleUpTime=2018-05-21 18:17:46.675599698 +0000 UTC lastScaleDownDeleteTime=2018-05-21 18:17:46.675599798 +0000 UTC lastScaleDownFailTime=2018-05-21 18:17:46.675599798 +0000 UTC schedulablePodsPresent=false isDeleteInProgress=false
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler

**This is verbose logging with triggering scale up:**
> static_autoscaler.go:114] Starting main loop
> azure_container_service_pool.go:86] AgentPool profile name: agentpool
> azure_container_service_pool.go:113] Got node count: 3
> azure_container_service_pool.go:393] Node Name: aks-agentpool-16882496-0, ID: /subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-0
> azure_container_service_pool.go:373] Matching agentPool name: agentpool with tag name: agentpool
> azure_container_service_pool.go:396] Returning back the providerID: azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-0
> azure_container_service_pool.go:393] Node Name: aks-agentpool-16882496-1, ID: /subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-1
> azure_container_service_pool.go:373] Matching agentPool name: agentpool with tag name: agentpool
> azure_container_service_pool.go:396] Returning back the providerID: azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-1
> azure_container_service_pool.go:393] Node Name: aks-agentpool-16882496-2, ID: /subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-2
> azure_container_service_pool.go:373] Matching agentPool name: agentpool with tag name: agentpool
> azure_container_service_pool.go:396] Returning back the providerID: azure:///subscriptions/3e4f65c2-daba-4875-822c-ba571de3c5e4/resourceGroups/mc_inception_inception-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-16882496-2
> static_autoscaler.go:186] 3 unregistered nodes present
> utils.go:456] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
> static_autoscaler.go:263] Filtering out schedulables
> static_autoscaler.go:273] No schedulable pods
> scale_up.go:59] Pod default/php-apache-7ccc68c5cd-4rjgm is unschedulable
> scale_up.go:59] Pod default/php-apache-7ccc68c5cd-b9l7g is unschedulable
> azure_container_service_pool.go:86] AgentPool profile name: agentpool
> azure_container_service_pool.go:113] Got node count: 3
> scale_up.go:446] No node info for: agentpool
> **static_autoscaler.go:304] Failed to scale up: failed to find template node for node group agentpool**
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
> reflector.go:428] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:87: Watch close - *v1.Node total 111 items received
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
> reflector.go:428] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:87: Watch close - *v1.ReplicationController total 0 items received
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
> leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler

**Comment by kkmsft** [comment]
@tobiasrosenhoff  

I am trying to repro this in-house in a similar version cluster. Will get back to you.

Typically, in the clusters, I see the label marked as "kubernetes.azure.com/cluster=MC_node_resource_group", but in the tags in you cluster above, I don't see them. Will dig a deeper there too.

Meanwhile, if its possible, can you please make the node resourcegroup value  "MC_inception_inception-aks_westeurope" (note: the MC is capitalized like in the provider ID in your config), although the instructions talk about about small letters ?

**Comment by tobiasrosenhoff** [comment]
@kkmsft @feiskyer 
After changing NodeResourceGroup, from mc_inception_inception-aks_westeurope to MC_inception_inception-aks_westeurope it now seems to be working. The scale up event was successful and I got another node. The scale down seems to be taking some time tho. I'll get back if that don't work. 

The documentation stats that NodeResourceGroup should be in lowercase, so maybe that should be corrected?

**Comment by kkmsft** [comment]
@tobiasrosenhoff 

Thank you for trying this out. Good to know that scale up worked. 

Will fix the documentation issue.

One quick question: Can you please confirm that in your cluster, the "kubernetes.azure.com/cluster" label is missing (kubectl get nodes --show-labels) ?

**Comment by feiskyer** [comment]
@tobiasrosenhoff Glad to see issues fixed

**Comment by feiskyer** [comment]
let's close this issue since it has been resolved

/close

**Comment by ChMarco** [comment]
I have an issue with autoscaler seems that is missing some authorizations ... on the master it works ... 
I created even a separated namespace with a user but still the same  #issue
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}



logs deployment/cluster-autoscaler --namespace=test-autosc
I0527 20:37:59.475210       1 main.go:225] Cluster Autoscaler 0.6.0
F0527 20:37:59.487483       1 main.go:257] Failed to get nodes from apiserver: nodes is forbidden: User "system:serviceaccount:test-autosc:default" cannot list nodes at the cluster scope
goroutine 1 [running]:
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.stacks(0xc420139600, 0xc4206d8000, 0xbb, 0x1bf)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).output(0x39a6240, 0xc400000003, 0xc420207340, 0x390a66c, 0x7, 0x101, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).printf(0x39a6240, 0x3, 0x26e7790, 0x26, 0xc4206b7e88, 0x1, 0x1)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.Fatalf(0x26e7790, 0x26, 0xc4206b7e88, 0x1, 0x1)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:257 +0x48f

**Comment by feiskyer** [comment]
@ChMarco Seems you are using 0.6.0? Only v1.2.2 supports AKS now
